/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Release session state. Call in Vite's buildEnd hook. */
export declare function closeSession(sessionId: number): void

/**
 * Create a persistent watch session. Returns session ID.
 * Call this in Vite's configResolved hook.
 */
export declare function createSession(options: JsExtractOptions): number

/**
 * Cold extraction — returns JSON string of ExtractionOutput.
 * Use for: build-time extraction, CLI backing, one-off runs.
 */
export declare function extractAll(options: JsExtractOptions): Promise<string>

/**
 * Incremental extraction for a single changed file.
 * Returns JSON string of IncrementalUpdate.
 * Use for: Vite HMR hotUpdate.
 */
export declare function extractFileIncremental(filePath: string, sessionId: number, options: JsExtractOptions): Promise<string>

/**
 * Initialize a watch session with a full cold extraction.
 * Returns JSON string of ExtractionOutput.
 * Call this after create_session(), in configureServer.
 */
export declare function initializeSession(sessionId: number, options: JsExtractOptions): Promise<string>

/** Options passed from TypeScript — flat struct for easy NAPI marshalling. */
export interface JsExtractOptions {
  srcDirs: Array<string>
  exclude?: Array<string>
  reactVersion?: 'react18' | 'react19'
  crossPackage?: boolean
  pandacssOutdir?: string
  variantFunctions?: Array<string>
  htmlAttributes?: 'curated' | 'full' | 'none'
  tsconfigPath?: string
  extraBuiltins?: Array<string>
  vanillaExtract?: boolean
  cacheDir?: string
  resolveComplexTypes?: boolean
  /** JSON: Record<string, string[]> */
  extraPathsJson?: string
  /** JSON: Record<string, {kind: ...}> */
  knownTypeOverridesJson?: string
}
