// Hand-maintained — NOT regenerated by `napi build`. The auto-generated NAPI
// function signatures (extractAll, JsExtractOptions, etc.) live in binding.d.ts,
// rebuilt fresh from the Rust #[napi] annotations on every `pnpm run build:napi`.
// This file re-exports those plus the hand-written shape of the JSON string
// each function resolves to (ExtractionOutput et al. — opaque to NAPI-RS's
// codegen since it only sees `Promise<string>` at the FFI boundary).
// Matches crates/core/src/types.rs.
export * from './binding'

export interface InheritedLayer {
  typeName: string
  fileName: string
  omitted: string[]
  htmlElement: string | null
  totalProps: number
}

export interface PropParent {
  name: string
  fileName: string
}

export interface DefaultValue {
  value: string
  computed: boolean
}

export type OpaqueReason =
  | { type: 'conditionalType' }
  | { type: 'mappedType' }
  | { type: 'moduleAugmentation' }
  | { type: 'runtimeDependent'; functionName: string }
  | { type: 'unresolvableImport'; specifier: string }
  | { type: 'pandaCodegenMissing' }
  | { type: 'depthExceeded' }
  | { type: 'indexedAccess'; expression: string }
  | { type: 'templateLiteral'; expression: string }

export interface ObjectField {
  name: string
  propType: PropType
  required: boolean
  description: string
}

export type PropType =
  | { kind: 'string' }
  | { kind: 'number' }
  | { kind: 'boolean' }
  | { kind: 'null' }
  | { kind: 'undefined' }
  | { kind: 'any' }
  | { kind: 'never' }
  | { kind: 'unknown' }
  | { kind: 'void' }
  | { kind: 'reactNode' }
  | { kind: 'cssProperties' }
  | { kind: 'elementType' }
  | { kind: 'sxProps' }
  | { kind: 'stringLiteral'; value: string }
  | { kind: 'numberLiteral'; value: number }
  | { kind: 'boolLiteral'; value: boolean }
  | { kind: 'union'; members: PropType[] }
  | { kind: 'intersection'; members: PropType[] }
  | { kind: 'array'; element: PropType }
  | { kind: 'tuple'; elements: PropType[] }
  | { kind: 'object'; fields: ObjectField[] }
  | { kind: 'named'; name: string; args: PropType[] }
  | { kind: 'eventHandler'; eventType: string; paramName: string | null }
  | { kind: 'ref'; element: string | null }
  | { kind: 'htmlAttributes'; element: string; omitted: string[] }
  | { kind: 'literalUnion'; members: string[]; hasDefault: boolean }
  | { kind: 'opaque'; raw: string; reason: OpaqueReason }

export interface ParsedProp {
  name: string
  type: PropType
  required: boolean
  defaultValue: DefaultValue | null
  description: string
  tags: Record<string, string>
  parent: PropParent | null
  declarations: PropParent[]
}

export interface ComponentEntry {
  displayName: string
  filePath: string
  description: string
  props: Record<string, ParsedProp>
  inheritance: InheritedLayer[]
  notableInherited: Record<string, ParsedProp>
  discriminantProp: string | null
  composes: string[]
  tags: Record<string, string>
  methods: []
}

export interface EnumEntry {
  name: string
  value: string | number | boolean
  description: string
}

export interface Diagnostic {
  severity: 'error' | 'warning' | 'info'
  message: string
  file: string | null
  line: number | null
  column: number | null
  help: string | null
  code: string
}

export interface ExtractionStats {
  componentsExtracted: number
  componentsSkipped: number
  filesParsed: number
  dtsFilesParsed: number
  dtsCacheHits: number
  durationMs: number
  tier1Count: number
  tier3Count: number
  opaqueCount: number
}

export interface ExtractionOutput {
  components: Record<string, ComponentEntry>
  enums: Record<string, EnumEntry[]>
  diagnostics: Diagnostic[]
  stats: ExtractionStats
}

export interface IncrementalUpdate {
  updatedComponents: ComponentEntry[]
  affectedFiles: string[]
  diagnostics: Diagnostic[]
  durationMs: number
}
