[package]
name = "oxc-react-docgen-napi"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
oxc-react-docgen-core = { path = "../core", version = "0.1.0" }
napi = { workspace = true, features = ["tokio_rt"] }
napi-derive.workspace  = true
serde_json.workspace   = true
dashmap.workspace      = true
camino.workspace       = true
compact_str.workspace  = true
tokio.workspace        = true

[build-dependencies]
napi-build = "2"
